version: '2'
services:

  redis:
    image: "redis:latest"

  nginx:
    image: "nginx:latest"
    env_file:
      - ./.env
    ports:
      - "80:80"
    volumes:
      - ${PROJECT_ROOT}:${GUEST_ROOT}
      - ./sites-enabled:/etc/nginx/sites-enabled
      - ./sites-enabled:/etc/nginx/sites-available
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - php

  php:
    build: ./fpm
    env_file:
      - ./.env
    volumes:
      - ${PROJECT_ROOT}:${GUEST_ROOT}
      - ./fpm/php.ini:/usr/local/etc/php/php.ini
    links:
      - mysql
      - mailhog
      - redis

  mysql:
    image: mariadb:latest
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"

  mailhog:
    image: "mailhog/mailhog"
    ports:
      - "8025:8025"